const examData = [
  {
    "id": 1,
    "title": "Đề 1",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 6 chục và 4 đơn vị là:\nA. 46<br>B. 64<br>C. 60<br>D. 40\n\n**Câu 2.** Số 89 đọc là:\nA. tám chín<br>B. tám mươi chín<br>C. chín mươi tám<br>D. tám mươi\n\n**Câu 3.** Số lớn nhất trong các số 72, 27, 70, 79 là:\nA. 72<br>B. 27<br>C. 70<br>D. 79\n\n**Câu 4.** Kết quả của 35 + 20 là:\nA. 37<br>B. 55<br>C. 53<br>D. 15\n\n**Câu 5.** Hôm nay là thứ Ba, ngày 12 tháng 4. Ngày mai là:\nA. thứ Tư, ngày 13 tháng 4<br>B. thứ Hai, ngày 11 tháng 4<br>C. thứ Ba, ngày 13 tháng 4<br>D. thứ Năm, ngày 14 tháng 4\n\n**Câu 6.** Hình nào có 4 cạnh bằng nhau?\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 48, 84, 54, 45 theo thứ tự bé đến lớn.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 46 + 23 = ............<br>b. 78 - 35 = ............\nc. 30 + 49 = ............<br>d. 96 - 40 = ............\n\n**Câu 9.** Lan có 24 viên bi, Minh có 15 viên bi. Hỏi hai bạn có tất cả bao nhiêu viên bi?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, = vào chỗ chấm:\na. 57 ... 75<br>b. 68 - 20 ... 48<br>c. 34 + 5 ... 40<br>d. 90 ... 89\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. B  \n3. D  \n4. B  \n5. A  \n6. C  \n\n### II. Tự luận\n**Câu 7:** 45, 48, 54, 84.  \n\n**Câu 8:**  \na. 69  \nb. 43  \nc. 79  \nd. 56  \n\n**Câu 9:**  \nSố viên bi hai bạn có tất cả là:  \n24 + 15 = 39 (viên bi)  \nĐáp số: 39 viên bi.  \n\n**Câu 10:**  \na. <  \nb. =  \nc. <  \nd. >  \n"
  },
  {
    "id": 2,
    "title": "Đề 2",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 53 gồm:\nA. 5 chục 3 đơn vị<br>B. 3 chục 5 đơn vị<br>C. 5 đơn vị 3 chục<br>D. 50 chục 3 đơn vị\n\n**Câu 2.** Số liền trước của 70 là:\nA. 71<br>B. 69<br>C. 60<br>D. 79\n\n**Câu 3.** Kết quả của 86 - 4 là:\nA. 82<br>B. 80<br>C. 46<br>D. 90\n\n**Câu 4.** Các số 31, 33, 35, ... Số cần điền là:\nA. 34<br>B. 36<br>C. 37<br>D. 38\n\n**Câu 5.** Đồng hồ chỉ 8 giờ đúng khi:\nA. kim ngắn chỉ 8, kim dài chỉ 12<br>B. kim ngắn chỉ 12, kim dài chỉ 8<br>C. kim ngắn chỉ 6, kim dài chỉ 12<br>D. kim ngắn chỉ 8, kim dài chỉ 6\n\n**Câu 6.** Trong các hình: hình tròn, hình tam giác, hình vuông, hình chữ nhật, hình không có cạnh là:\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Viết các số: ba mươi bảy, sáu mươi mốt, chín mươi, năm mươi tám.\n........................................................................\n\n**Câu 8.** Tính:\na. 42 + 17 = ............<br>b. 95 - 52 = ............\nc. 61 + 8 = .............<br>d. 77 - 7 = .............\n\n**Câu 9.** Trong vườn có 36 cây hoa hồng và 20 cây hoa cúc. Hỏi trong vườn có tất cả bao nhiêu cây hoa?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 45 = 40 + ...<br>b. 68 = ... + 8<br>c. 90 = 9 chục và ... đơn vị<br>d. 7 chục 2 đơn vị = ...\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. B  \n3. A  \n4. C  \n5. A  \n6. A  \n\n### II. Tự luận\n**Câu 7:** 37, 61, 90, 58.  \n\n**Câu 8:**  \na. 59  \nb. 43  \nc. 69  \nd. 70  \n\n**Câu 9:**  \nSố cây hoa trong vườn có tất cả là:  \n36 + 20 = 56 (cây hoa)  \nĐáp số: 56 cây hoa.  \n\n**Câu 10:**  \na. 5  \nb. 60  \nc. 0  \nd. 72  \n"
  },
  {
    "id": 3,
    "title": "Đề 3",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 76 đọc là:\nA. bảy sáu<br>B. bảy mươi sáu<br>C. sáu mươi bảy<br>D. bảy mươi\n\n**Câu 2.** Số bé nhất trong các số 64, 46, 60, 69 là:\nA. 64<br>B. 46<br>C. 60<br>D. 69\n\n**Câu 3.** Kết quả của 40 + 30 là:\nA. 43<br>B. 70<br>C. 10<br>D. 73\n\n**Câu 4.** 58 - ... = 50. Số cần điền là:\nA. 5<br>B. 8<br>C. 50<br>D. 58\n\n**Câu 5.** Một tuần có:\nA. 5 ngày<br>B. 6 ngày<br>C. 7 ngày<br>D. 8 ngày\n\n**Câu 6.** Hình tam giác có:\nA. 2 cạnh<br>B. 3 cạnh<br>C. 4 cạnh<br>D. không có cạnh\n\n### II. Tự luận\n**Câu 7.** Điền dấu >, <, =:\na. 63 ... 36<br>b. 70 + 5 ... 75<br>c. 88 - 8 ... 79<br>d. 40 + 20 ... 62\n\n**Câu 8.** Đặt tính rồi tính:\na. 25 + 34 = ............<br>b. 89 - 27 = ............\nc. 56 + 3 = .............<br>d. 64 - 30 = ............\n\n**Câu 9.** Mẹ mua 45 quả cam, đã ăn 12 quả. Hỏi còn lại bao nhiêu quả cam?\nBài giải: ................................................................\n\n**Câu 10.** Vẽ thêm vào mỗi hình cho đủ:\na. Một hình vuông có 4 cạnh.  \nb. Một hình tam giác có 3 đỉnh.  \nc. Một hình chữ nhật có 4 góc.\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. B  \n3. B  \n4. B  \n5. C  \n6. B  \n\n### II. Tự luận\n**Câu 7:**  \na. >  \nb. =  \nc. >  \nd. <  \n\n**Câu 8:**  \na. 59  \nb. 62  \nc. 59  \nd. 34  \n\n**Câu 9:**  \nSố quả cam còn lại là:  \n45 - 12 = 33 (quả cam)  \nĐáp số: 33 quả cam.  \n\n**Câu 10:**  \nHọc sinh tự vẽ hình theo yêu cầu.\n"
  },
  {
    "id": 4,
    "title": "Đề 4",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 9 chục và 0 đơn vị là:\nA. 9<br>B. 90<br>C. 99<br>D. 09\n\n**Câu 2.** Số liền sau của 58 là:\nA. 57<br>B. 59<br>C. 68<br>D. 60\n\n**Câu 3.** Phép tính có kết quả bằng 47 là:\nA. 40 + 7<br>B. 47 - 7<br>C. 37 + 5<br>D. 57 - 20\n\n**Câu 4.** 93 - 40 =:\nA. 50<br>B. 53<br>C. 63<br>D. 97\n\n**Câu 5.** Nếu hôm qua là thứ Năm thì hôm nay là:\nA. thứ Tư<br>B. thứ Năm<br>C. thứ Sáu<br>D. thứ Bảy\n\n**Câu 6.** Độ dài của bút chì thường được đo bằng:\nA. cm<br>B. l<br>C. kg<br>D. giờ\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 90, 19, 91, 99 theo thứ tự lớn đến bé.\n........................................................................\n\n**Câu 8.** Tính:\na. 67 - 25 = ............<br>b. 38 + 41 = ............\nc. 80 - 30 = ............<br>d. 24 + 5 = .............\n\n**Câu 9.** Lớp 1A có 32 bạn nữ và 25 bạn nam. Hỏi lớp 1A có tất cả bao nhiêu bạn?\nBài giải: ................................................................\n\n**Câu 10.** Điền số vào chỗ chấm:\na. ... + 20 = 65<br>b. 78 - ... = 70<br>c. 30 + ... = 39<br>d. ... - 4 = 82\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. B  \n3. A  \n4. B  \n5. C  \n6. A  \n\n### II. Tự luận\n**Câu 7:** 99, 91, 90, 19.  \n\n**Câu 8:**  \na. 42  \nb. 79  \nc. 50  \nd. 29  \n\n**Câu 9:**  \nSố bạn lớp 1A có tất cả là:  \n32 + 25 = 57 (bạn)  \nĐáp số: 57 bạn.  \n\n**Câu 10:**  \na. 45  \nb. 8  \nc. 9  \nd. 86  \n"
  },
  {
    "id": 5,
    "title": "Đề 5",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 41 gồm:\nA. 4 chục 1 đơn vị<br>B. 1 chục 4 đơn vị<br>C. 4 đơn vị 1 chục<br>D. 41 chục\n\n**Câu 2.** 100 là số:\nA. có 1 chữ số<br>B. có 2 chữ số<br>C. có 3 chữ số<br>D. bé hơn 99\n\n**Câu 3.** Kết quả của 59 - 9 là:\nA. 50<br>B. 58<br>C. 49<br>D. 68\n\n**Câu 4.** Số cần điền: 22, 24, 26, ..., 30\nA. 27<br>B. 28<br>C. 29<br>D. 31\n\n**Câu 5.** 1 chục que tính là:\nA. 1 que<br>B. 10 que<br>C. 11 que<br>D. 100 que\n\n**Câu 6.** Hình chữ nhật có:\nA. 3 cạnh<br>B. 4 cạnh<br>C. 5 cạnh<br>D. không có cạnh\n\n### II. Tự luận\n**Câu 7.** Viết số thích hợp vào chỗ chấm:\na. 6 chục 7 đơn vị = ...<br>b. 4 chục 0 đơn vị = ...\nc. 82 = ... chục ... đơn vị<br>d. 95 = ... + ...\n\n**Câu 8.** Đặt tính rồi tính:\na. 52 + 16 = ............<br>b. 74 - 21 = ............\nc. 37 + 40 = ............<br>d. 98 - 6 = .............\n\n**Câu 9.** Nam có 58 nhãn vở. Nam cho bạn 20 nhãn vở. Hỏi Nam còn lại bao nhiêu nhãn vở?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, =:\na. 45 + 10 ... 54<br>b. 76 - 6 ... 70<br>c. 33 ... 30 + 3<br>d. 99 ... 100\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. C  \n3. A  \n4. B  \n5. B  \n6. B  \n\n### II. Tự luận\n**Câu 7:**  \na. 67  \nb. 40  \nc. 8 chục 2 đơn vị  \nd. 90 + 5  \n\n**Câu 8:**  \na. 68  \nb. 53  \nc. 77  \nd. 92  \n\n**Câu 9:**  \nSố nhãn vở Nam còn lại là:  \n58 - 20 = 38 (nhãn vở)  \nĐáp số: 38 nhãn vở.  \n\n**Câu 10:**  \na. >  \nb. =  \nc. =  \nd. <  \n"
  },
  {
    "id": 6,
    "title": "Đề 6",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 28 đọc là:\nA. hai tám<br>B. hai mươi tám<br>C. tám mươi hai<br>D. hai mươi\n\n**Câu 2.** Số lớn hơn 65 và bé hơn 67 là:\nA. 64<br>B. 65<br>C. 66<br>D. 67\n\n**Câu 3.** 70 + 6 =:\nA. 67<br>B. 76<br>C. 706<br>D. 13\n\n**Câu 4.** 84 - 30 =:\nA. 54<br>B. 81<br>C. 87<br>D. 50\n\n**Câu 5.** Tháng 5 có:\nA. 28 ngày<br>B. 29 ngày<br>C. 30 ngày<br>D. 31 ngày\n\n**Câu 6.** Vật nào thường có dạng hình tròn?\nA. mặt đồng hồ<br>B. quyển sách<br>C. bảng lớp<br>D. viên gạch\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 17, 71, 70, 77 theo thứ tự bé đến lớn.\n........................................................................\n\n**Câu 8.** Tính:\na. 64 + 25 = ............<br>b. 87 - 43 = ............\nc. 20 + 57 = ............<br>d. 69 - 9 = .............\n\n**Câu 9.** Bố có 40 con gà, mẹ mua thêm 18 con gà. Hỏi nhà em có tất cả bao nhiêu con gà?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 29, 30, 31, ..., 33<br>b. 80, 70, 60, ..., 40\nc. 15 + ... = 35<br>d. 96 - ... = 76\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. C  \n3. B  \n4. A  \n5. D  \n6. A  \n\n### II. Tự luận\n**Câu 7:** 17, 70, 71, 77.  \n\n**Câu 8:**  \na. 89  \nb. 44  \nc. 77  \nd. 60  \n\n**Câu 9:**  \nSố con gà nhà em có tất cả là:  \n40 + 18 = 58 (con gà)  \nĐáp số: 58 con gà.  \n\n**Câu 10:**  \na. 32  \nb. 50  \nc. 20  \nd. 20  \n"
  },
  {
    "id": 7,
    "title": "Đề 7",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 3 chục và 8 đơn vị là:\nA. 83<br>B. 38<br>C. 30<br>D. 8\n\n**Câu 2.** Số bé nhất có hai chữ số là:\nA. 1<br>B. 9<br>C. 10<br>D. 11\n\n**Câu 3.** Kết quả của 46 + 3 là:\nA. 43<br>B. 49<br>C. 76<br>D. 19\n\n**Câu 4.** 92 - 50 =:\nA. 42<br>B. 47<br>C. 52<br>D. 90\n\n**Câu 5.** Thứ Ba, thứ Tư, thứ Năm, ..., thứ Bảy. Từ còn thiếu là:\nA. thứ Hai<br>B. thứ Sáu<br>C. Chủ nhật<br>D. thứ Ba\n\n**Câu 6.** Hình nào có 3 đỉnh?\nA. hình tròn<br>B. hình vuông<br>C. hình tam giác<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Viết các số sau theo thứ tự từ 55 đến 60.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 31 + 48 = ............<br>b. 75 - 32 = ............\nc. 44 + 20 = ............<br>d. 89 - 7 = .............\n\n**Câu 9.** Trên cành cây có 27 con chim, sau đó có 12 con bay đi. Hỏi trên cành cây còn lại bao nhiêu con chim?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, =:\na. 60 ... 6 chục<br>b. 72 ... 27<br>c. 81 - 1 ... 79<br>d. 25 + 4 ... 30\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. C  \n3. B  \n4. A  \n5. B  \n6. C  \n\n### II. Tự luận\n**Câu 7:** 55, 56, 57, 58, 59, 60.  \n\n**Câu 8:**  \na. 79  \nb. 43  \nc. 64  \nd. 82  \n\n**Câu 9:**  \nSố con chim trên cành cây còn lại là:  \n27 - 12 = 15 (con chim)  \nĐáp số: 15 con chim.  \n\n**Câu 10:**  \na. =  \nb. >  \nc. >  \nd. <  \n"
  },
  {
    "id": 8,
    "title": "Đề 8",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 95 gồm:\nA. 9 chục 5 đơn vị<br>B. 5 chục 9 đơn vị<br>C. 9 đơn vị 5 chục<br>D. 95 đơn vị\n\n**Câu 2.** Số liền trước của 100 là:\nA. 98<br>B. 99<br>C. 101<br>D. 90\n\n**Câu 3.** Kết quả của 23 + 34 là:\nA. 57<br>B. 56<br>C. 47<br>D. 67\n\n**Câu 4.** Phép tính nào có kết quả bé nhất?\nA. 40 + 5<br>B. 60 - 10<br>C. 30 + 8<br>D. 70 - 20\n\n**Câu 5.** Kim dài chỉ số 12, kim ngắn chỉ số 5. Đồng hồ chỉ:\nA. 12 giờ<br>B. 5 giờ<br>C. 6 giờ<br>D. 10 giờ\n\n**Câu 6.** Hình nào có 4 góc?\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. đoạn thẳng\n\n### II. Tự luận\n**Câu 7.** Điền số vào tia số:\n41, 42, ..., 44, ..., 46, ...\n\n**Câu 8.** Tính:\na. 58 + 21 = ............<br>b. 97 - 54 = ............\nc. 70 + 9 = .............<br>d. 86 - 6 = .............\n\n**Câu 9.** Cửa hàng có 65 hộp sữa, đã bán 30 hộp. Hỏi cửa hàng còn lại bao nhiêu hộp sữa?\nBài giải: ................................................................\n\n**Câu 10.** Viết tiếp vào chỗ chấm:\na. 3 ngày trong tuần: ...................................................\nb. 2 vật có dạng hình chữ nhật: .........................................\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. B  \n3. A  \n4. C  \n5. B  \n6. C  \n\n### II. Tự luận\n**Câu 7:** 43, 45, 47.  \n\n**Câu 8:**  \na. 79  \nb. 43  \nc. 79  \nd. 80  \n\n**Câu 9:**  \nSố hộp sữa cửa hàng còn lại là:  \n65 - 30 = 35 (hộp sữa)  \nĐáp số: 35 hộp sữa.  \n\n**Câu 10:**  \na. Ví dụ: thứ Hai, thứ Ba, thứ Tư.  \nb. Ví dụ: quyển sách, cái bàn.  \n"
  },
  {
    "id": 9,
    "title": "Đề 9",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 60 đọc là:\nA. sáu mươi<br>B. sáu không<br>C. sáu chục<br>D. không sáu\n\n**Câu 2.** Trong các số 81, 18, 80, 88, số lớn nhất là:\nA. 81<br>B. 18<br>C. 80<br>D. 88\n\n**Câu 3.** 36 + 12 =:\nA. 48<br>B. 46<br>C. 58<br>D. 24\n\n**Câu 4.** 79 - 20 =:\nA. 57<br>B. 59<br>C. 99<br>D. 70\n\n**Câu 5.** Hôm nay là ngày 16 tháng 3. Ngày hôm qua là:\nA. ngày 15 tháng 3<br>B. ngày 17 tháng 3<br>C. ngày 16 tháng 4<br>D. ngày 14 tháng 3\n\n**Câu 6.** Một đoạn thẳng có:\nA. 1 đầu mút<br>B. 2 đầu mút<br>C. 3 đầu mút<br>D. 4 đầu mút\n\n### II. Tự luận\n**Câu 7.** Viết các số 64, 46, 60, 69 theo thứ tự lớn đến bé.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 43 + 25 = ............<br>b. 88 - 36 = ............\nc. 50 + 28 = ............<br>d. 76 - 5 = .............\n\n**Câu 9.** Mai gấp được 34 ngôi sao, Hoa gấp được 23 ngôi sao. Hỏi hai bạn gấp được tất cả bao nhiêu ngôi sao?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 57 = ... + 7<br>b. 81 = 80 + ...<br>c. 48 - ... = 40<br>d. ... + 30 = 92\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. D  \n3. A  \n4. B  \n5. A  \n6. B  \n\n### II. Tự luận\n**Câu 7:** 69, 64, 60, 46.  \n\n**Câu 8:**  \na. 68  \nb. 52  \nc. 78  \nd. 71  \n\n**Câu 9:**  \nSố ngôi sao hai bạn gấp được tất cả là:  \n34 + 23 = 57 (ngôi sao)  \nĐáp số: 57 ngôi sao.  \n\n**Câu 10:**  \na. 50  \nb. 1  \nc. 8  \nd. 62  \n"
  },
  {
    "id": 10,
    "title": "Đề 10",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 8 chục và 2 đơn vị là:\nA. 28<br>B. 82<br>C. 80<br>D. 20\n\n**Câu 2.** Số liền sau của 99 là:\nA. 98<br>B. 90<br>C. 100<br>D. 109\n\n**Câu 3.** Kết quả của 72 - 2 là:\nA. 70<br>B. 74<br>C. 52<br>D. 20\n\n**Câu 4.** Phép tính nào có kết quả bằng 66?\nA. 60 + 6<br>B. 66 - 6<br>C. 56 + 6<br>D. 76 - 20\n\n**Câu 5.** Thứ tự đúng của các tháng là:\nA. tháng 1, tháng 2, tháng 3<br>B. tháng 2, tháng 1, tháng 3<br>C. tháng 3, tháng 2, tháng 1<br>D. tháng 1, tháng 3, tháng 2\n\n**Câu 6.** Vật nào thường có dạng hình vuông?\nA. mặt đồng hồ tròn<br>B. viên gạch lát nền<br>C. quả bóng<br>D. cái bút\n\n### II. Tự luận\n**Câu 7.** Điền dấu >, <, =:\na. 45 ... 54<br>b. 90 - 10 ... 80<br>c. 67 + 2 ... 70<br>d. 100 ... 99\n\n**Câu 8.** Tính:\na. 36 + 42 = ............<br>b. 94 - 31 = ............\nc. 63 + 6 = .............<br>d. 85 - 40 = ............\n\n**Câu 9.** Thu có 56 bông hoa, Thu tặng bạn 24 bông. Hỏi Thu còn lại bao nhiêu bông hoa?\nBài giải: ................................................................\n\n**Câu 10.** Quan sát và trả lời:\na. Hình vuông có .... cạnh.  \nb. Hình tam giác có .... cạnh.  \nc. Hình tròn có .... cạnh.  \nd. Hình chữ nhật có .... góc.\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. C  \n3. A  \n4. A  \n5. A  \n6. B  \n\n### II. Tự luận\n**Câu 7:**  \na. <  \nb. =  \nc. <  \nd. >  \n\n**Câu 8:**  \na. 78  \nb. 63  \nc. 69  \nd. 45  \n\n**Câu 9:**  \nSố bông hoa Thu còn lại là:  \n56 - 24 = 32 (bông hoa)  \nĐáp số: 32 bông hoa.  \n\n**Câu 10:**  \na. 4  \nb. 3  \nc. 0 (hoặc không có cạnh)  \nd. 4  \n"
  }
];\n\n// Các Đề Nâng Cao\nconst advancedExamData = [
  {
    "id": 11,
    "title": "Đề Nâng Cao 1",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số lớn nhất có hai chữ số khác nhau là:\nA. 99<br>B. 98<br>C. 89<br>D. 90\n\n**Câu 2.** Số bé nhất có hai chữ số mà chữ số hàng chục lớn hơn chữ số hàng đơn vị là:\nA. 10<br>B. 11<br>C. 20<br>D. 21\n\n**Câu 3.** Kết quả của 45 + 12 - 20 là:\nA. 37<br>B. 47<br>C. 57<br>D. 77\n\n**Câu 4.** Biểu thức nào có kết quả lớn nhất?\nA. 70 - 20<br>B. 36 + 12<br>C. 90 - 30<br>D. 25 + 24\n\n**Câu 5.** Dãy số 18, 28, 38, ..., 58. Số còn thiếu là:\nA. 39<br>B. 40<br>C. 48<br>D. 50\n\n**Câu 6.** Có 2 hình tam giác riêng biệt ghép thành 1 hình tam giác lớn. Tổng số hình tam giác đếm được là:\nA. 2<br>B. 3<br>C. 4<br>D. 5\n\n### II. Tự luận\n**Câu 7.** Điền dấu >, <, =:\na. 68 - 20 ... 35 + 13<br>b. 90 - 40 ... 20 + 31\nc. 47 + 2 ... 60 - 10<br>d. 88 - 8 ... 70 + 10\n\n**Câu 8.** Tìm số thích hợp:\na. ... + 25 = 68<br>b. 79 - ... = 34\nc. 40 + ... + 6 = 96<br>d. ... - 30 = 52\n\n**Câu 9.** Lan có 36 bông hoa. Lan tặng Mai 12 bông, sau đó mẹ cho Lan thêm 20 bông. Hỏi Lan có bao nhiêu bông hoa?\nBài giải: ................................................................\n\n**Câu 10.** Viết tất cả các số có hai chữ số được lập từ 3 và 7. Sắp xếp các số đó từ bé đến lớn.\n........................................................................\n",
    "answer": "### I. Trắc nghiệm\n1. B\n2. A\n3. A\n4. C\n5. C\n6. B\n\n### II. Tự luận\n**Câu 7:**\na. <\nb. <\nc. <\nd. =\n\n**Câu 8:**\na. 43\nb. 45\nc. 50\nd. 82\n\n**Câu 9:**\nSố bông hoa Lan có là:\n36 - 12 + 20 = 44 (bông hoa)\nĐáp số: 44 bông hoa.\n\n**Câu 10:**\n33, 37, 73, 77.\n"
  },
  {
    "id": 12,
    "title": "Đề Nâng Cao 2",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào vừa lớn hơn 56 vừa bé hơn 60?\nA. 55<br>B. 56<br>C. 58<br>D. 60\n\n**Câu 2.** 8 chục 5 đơn vị bớt 3 chục là:\nA. 55<br>B. 58<br>C. 82<br>D. 85\n\n**Câu 3.** 23 + 45 - 8 =:\nA. 50<br>B. 60<br>C. 68<br>D. 76\n\n**Câu 4.** Số cần điền vào dãy 92, 82, 72, ..., 52 là:\nA. 62<br>B. 63<br>C. 70<br>D. 80\n\n**Câu 5.** Nếu hôm nay là thứ Bảy thì sau 2 ngày nữa là:\nA. thứ Bảy<br>B. Chủ nhật<br>C. thứ Hai<br>D. thứ Ba\n\n**Câu 6.** Hình vuông và hình chữ nhật giống nhau ở điểm:\nA. đều có 3 cạnh<br>B. đều có 4 góc<br>C. đều không có cạnh<br>D. đều là hình tròn\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 86, 68, 80, 88, 60 theo thứ tự lớn đến bé.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 34 + 25 = ............<br>b. 97 - 53 = ............\nc. 56 + 31 = ............<br>d. 88 - 46 = ............\n\n**Câu 9.** Trong hộp có 48 viên kẹo. Kem ăn 15 viên, rồi bỏ thêm vào hộp 10 viên. Hỏi trong hộp có bao nhiêu viên kẹo?\nBài giải: ................................................................\n\n**Câu 10.** Điền số:\na. 15 + ... = 45 + 10<br>b. 90 - ... = 36 + 14\nc. ... - 20 = 27 + 30<br>d. 42 + ... = 80 - 8\n",
    "answer": "### I. Trắc nghiệm\n1. C\n2. A\n3. B\n4. A\n5. C\n6. B\n\n### II. Tự luận\n**Câu 7:**\n88, 86, 80, 68, 60.\n\n**Câu 8:**\na. 59\nb. 44\nc. 87\nd. 42\n\n**Câu 9:**\nSố viên kẹo trong hộp có là:\n48 - 15 + 10 = 43 (viên kẹo)\nĐáp số: 43 viên kẹo.\n\n**Câu 10:**\na. 40\nb. 40\nc. 77\nd. 30\n"
  },
  {
    "id": 13,
    "title": "Đề Nâng Cao 3",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào có chữ số hàng chục bé hơn chữ số hàng đơn vị?\nA. 72<br>B. 64<br>C. 39<br>D. 91\n\n**Câu 2.** Tổng của 40, 5 và 23 là:\nA. 58<br>B. 68<br>C. 73<br>D. 86\n\n**Câu 3.** 96 - 30 - 6 =:\nA. 50<br>B. 60<br>C. 66<br>D. 72\n\n**Câu 4.** Biểu thức nào bằng 75?\nA. 70 + 6<br>B. 95 - 20<br>C. 45 + 20<br>D. 80 - 4\n\n**Câu 5.** Trong các số 57, 75, 70, 77, số có hàng chục lớn nhất và hàng đơn vị nhỏ nhất là:\nA. 57<br>B. 75<br>C. 70<br>D. 77\n\n**Câu 6.** Một hình chữ nhật cắt bởi 1 đường thẳng thành 2 hình nhỏ. Nếu đường cắt nối 2 góc đối nhau thì tạo thành:\nA. 2 hình tam giác<br>B. 2 hình tròn<br>C. 2 hình vuông<br>D. 1 hình tròn\n\n### II. Tự luận\n**Câu 7.** Viết các số có hai chữ số mà hàng chục là 6, hàng đơn vị lớn hơn 5.\n........................................................................\n\n**Câu 8.** Điền dấu >, <, =:\na. 64 + 20 ... 90 - 6<br>b. 55 - 5 ... 20 + 29\nc. 32 + 46 ... 88 - 10<br>d. 100 - 40 ... 30 + 31\n\n**Câu 9.** Nam có 27 viên bi. Bình có nhiều hơn Nam 12 viên bi. Hỏi Bình có bao nhiêu viên bi? Hai bạn có tất cả bao nhiêu viên bi?\nBài giải: ................................................................\n\n**Câu 10.** Tìm x:\na. x + 14 = 59<br>b. x - 22 = 35<br>c. 80 - x = 50<br>d. 36 + x = 78\n",
    "answer": "### I. Trắc nghiệm\n1. C\n2. B\n3. B\n4. B\n5. C\n6. A\n\n### II. Tự luận\n**Câu 7:**\n66, 67, 68, 69.\n\n**Câu 8:**\na. =\nb. >\nc. =\nd. <\n\n**Câu 9:**\nSố viên bi Bình có là:\n27 + 12 = 39 (viên bi)\nSố viên bi hai bạn có tất cả là:\n27 + 39 = 66 (viên bi)\nĐáp số: 39 viên bi; 66 viên bi.\n\n**Câu 10:**\na. x = 45\nb. x = 57\nc. x = 30\nd. x = 42\n"
  },
  {
    "id": 14,
    "title": "Đề Nâng Cao 4",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào gần 70 nhất?\nA. 59<br>B. 67<br>C. 82<br>D. 90\n\n**Câu 2.** 4 chục + 5 chục + 7 đơn vị =:\nA. 47<br>B. 57<br>C. 90<br>D. 97\n\n**Câu 3.** 84 - 12 + 6 =:\nA. 66<br>B. 72<br>C. 78<br>D. 90\n\n**Câu 4.** Nếu 37 + ... = 67 thì số cần điền là:\nA. 20<br>B. 30<br>C. 40<br>D. 50\n\n**Câu 5.** Thứ Năm, thứ Sáu, thứ Bảy, ..., thứ Hai. Từ còn thiếu là:\nA. thứ Tư<br>B. Chủ nhật<br>C. thứ Ba<br>D. thứ Năm\n\n**Câu 6.** Có 1 hình vuông lớn chia thành 4 hình vuông nhỏ bằng nhau. Đếm được tất cả:\nA. 4 hình vuông<br>B. 5 hình vuông<br>C. 6 hình vuông<br>D. 8 hình vuông\n\n### II. Tự luận\n**Câu 7.** Điền số vào chỗ chấm:\na. 24, 34, 44, ..., ..., 74\nb. 99, 89, 79, ..., ..., 49\n\n**Câu 8.** Đặt tính rồi tính:\na. 62 + 27 = ............<br>b. 94 - 41 = ............\nc. 25 + 53 = ............<br>d. 86 - 35 = ............\n\n**Câu 9.** Giá sách có 56 quyển truyện. Kem đọc 14 quyển, sau đó ba mua thêm 22 quyển. Hỏi giá sách có bao nhiêu quyển truyện?\nBài giải: ................................................................\n\n**Câu 10.** Viết 4 số có hai chữ số mà tổng hai chữ số bằng 9.\n........................................................................\n",
    "answer": "### I. Trắc nghiệm\n1. B\n2. D\n3. C\n4. B\n5. B\n6. B\n\n### II. Tự luận\n**Câu 7:**\na. 54, 64\nb. 69, 59\n\n**Câu 8:**\na. 89\nb. 53\nc. 78\nd. 51\n\n**Câu 9:**\nSố quyển truyện giá sách có là:\n56 - 14 + 22 = 64 (quyển truyện)\nĐáp số: 64 quyển truyện.\n\n**Câu 10:**\nCó thể viết: 18, 27, 36, 45 (hoặc 54, 63, 72, 81, 90).\n"
  },
  {
    "id": 15,
    "title": "Đề Nâng Cao 5",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào có tổng hai chữ số bằng 13?\nA. 39<br>B. 49<br>C. 57<br>D. 66\n\n**Câu 2.** Số lớn nhất trong các số có hàng chục là 8 là:\nA. 80<br>B. 88<br>C. 89<br>D. 98\n\n**Câu 3.** 100 - 30 - 20 =:\nA. 40<br>B. 50<br>C. 60<br>D. 70\n\n**Câu 4.** 17 + 22 + 30 =:\nA. 59<br>B. 69<br>C. 79<br>D. 89\n\n**Câu 5.** Hôm nay là ngày 28 tháng 4. Ngày mai là:\nA. ngày 27 tháng 4<br>B. ngày 29 tháng 4<br>C. ngày 30 tháng 4<br>D. ngày 1 tháng 5\n\n**Câu 6.** Hình nào có thể lăn được?\nA. hình tròn<br>B. hình vuông<br>C. hình tam giác<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Viết số theo yêu cầu:\na. Số lớn nhất có hai chữ số: ...\nb. Số bé nhất có hai chữ số: ...\nc. Số liền trước của 80: ...\nd. Số liền sau của 89: ...\n\n**Câu 8.** Tính:\na. 73 - 21 + 5 = ............<br>b. 46 + 30 - 12 = ............\nc. 90 - 40 + 18 = ............<br>d. 25 + 24 + 10 = ............\n\n**Câu 9.** Trên sân có 18 con vịt và 21 con gà. Sau đó 10 con gà vào chuồng. Hỏi trên sân còn lại bao nhiêu con vật?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, =:\na. 36 + 42 ... 80<br>b. 99 - 9 ... 90<br>c. 45 + 14 ... 60<br>d. 70 - 5 ... 60 + 6\n",
    "answer": "### I. Trắc nghiệm\n1. B\n2. C\n3. B\n4. B\n5. B\n6. A\n\n### II. Tự luận\n**Câu 7:**\na. 99\nb. 10\nc. 79\nd. 90\n\n**Câu 8:**\na. 57\nb. 64\nc. 68\nd. 59\n\n**Câu 9:**\nSố con vật trên sân còn lại là:\n18 + 21 - 10 = 29 (con vật)\nĐáp số: 29 con vật.\n\n**Câu 10:**\na. <\nb. =\nc. <\nd. <\n"
  },
  {
    "id": 16,
    "title": "Đề Nâng Cao 6",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào vừa có hàng chục là 7 vừa lớn hơn 75?\nA. 70<br>B. 74<br>C. 76<br>D. 85\n\n**Câu 2.** Hiệu của 88 và 35 là:\nA. 43<br>B. 53<br>C. 63<br>D. 123\n\n**Câu 3.** Tổng của 26 và 43 rồi bớt 20 là:\nA. 49<br>B. 59<br>C. 69<br>D. 89\n\n**Câu 4.** Số cần điền: 11, 22, 33, ..., 55\nA. 34<br>B. 40<br>C. 44<br>D. 45\n\n**Câu 5.** Sau 3 ngày nữa kể từ thứ Hai là:\nA. thứ Ba<br>B. thứ Tư<br>C. thứ Năm<br>D. thứ Sáu\n\n**Câu 6.** Có 3 đoạn thẳng nối 3 điểm khác nhau thành một hình kín. Hình đó là:\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Tìm số bị che:\na. 6... > 65 và < 68: ...<br>b. ...4 > 70 và < 80: ...\nc. 9... < 93 và > 90: ...<br>d. ...0 = 8 chục: ...\n\n**Câu 8.** Đặt tính rồi tính:\na. 41 + 38 = ............<br>b. 76 - 24 = ............\nc. 53 + 26 = ............<br>d. 99 - 57 = ............\n\n**Câu 9.** Có 65 quả táo trong giỏ. Ban đầu lấy ra 20 quả, sau đó lại lấy thêm 13 quả. Hỏi trong giỏ còn bao nhiêu quả táo?\nBài giải: ................................................................\n\n**Câu 10.** Sắp xếp kết quả các phép tính sau từ bé đến lớn:\n45 + 10; 90 - 40; 23 + 34; 88 - 30.\n........................................................................\n",
    "answer": "### I. Trắc nghiệm\n1. C\n2. B\n3. A\n4. C\n5. C\n6. B\n\n### II. Tự luận\n**Câu 7:**\na. 66 hoặc 67\nb. 74\nc. 91 hoặc 92\nd. 80\n\n**Câu 8:**\na. 79\nb. 52\nc. 79\nd. 42\n\n**Câu 9:**\nSố quả táo trong giỏ còn lại là:\n65 - 20 - 13 = 32 (quả táo)\nĐáp số: 32 quả táo.\n\n**Câu 10:**\nCác kết quả: 55; 50; 57; 58.\nSắp xếp: 90 - 40, 45 + 10, 23 + 34, 88 - 30.\n"
  },
  {
    "id": 17,
    "title": "Đề Nâng Cao 7",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số có hai chữ số giống nhau và lớn hơn 80 là:\nA. 77<br>B. 80<br>C. 88<br>D. 98\n\n**Câu 2.** 5 chục 6 đơn vị thêm 3 chục 2 đơn vị là:\nA. 78<br>B. 88<br>C. 89<br>D. 98\n\n**Câu 3.** 69 - 20 + 10 =:\nA. 39<br>B. 49<br>C. 59<br>D. 79\n\n**Câu 4.** Phép tính nào có kết quả bé hơn 50?\nA. 70 - 20<br>B. 36 + 14<br>C. 88 - 40<br>D. 41 + 9\n\n**Câu 5.** Tháng có 30 ngày là:\nA. tháng 2<br>B. tháng 4<br>C. tháng 5<br>D. tháng 7\n\n**Câu 6.** Nếu vẽ thêm 1 đường thẳng nối hai đỉnh đối nhau của hình vuông, ta được:\nA. 2 hình tam giác<br>B. 2 hình tròn<br>C. 3 hình vuông<br>D. 4 hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Điền số thích hợp:\na. 100 = ... chục<br>b. 73 = ... + 3\nc. 6 chục 9 đơn vị = ...<br>d. 85 = ... chục ... đơn vị\n\n**Câu 8.** Tìm x:\na. x + 20 = 86<br>b. 75 - x = 25<br>c. x - 13 = 46<br>d. 34 + x = 89\n\n**Câu 9.** Trong bể có 24 con cá vàng và 15 con cá đỏ. Mẹ mua thêm 20 con cá nữa. Hỏi trong bể có tất cả bao nhiêu con cá?\nBài giải: ................................................................\n\n**Câu 10.** Viết các số có hai chữ số, hàng chục là 4, hàng đơn vị là số chẵn.\n........................................................................\n",
    "answer": "### I. Trắc nghiệm\n1. C\n2. B\n3. C\n4. C\n5. B\n6. A\n\n### II. Tự luận\n**Câu 7:**\na. 10\nb. 70\nc. 69\nd. 8 chục 5 đơn vị\n\n**Câu 8:**\na. x = 66\nb. x = 50\nc. x = 59\nd. x = 55\n\n**Câu 9:**\nSố con cá trong bể có tất cả là:\n24 + 15 + 20 = 59 (con cá)\nĐáp số: 59 con cá.\n\n**Câu 10:**\n40, 42, 44, 46, 48.\n"
  },
  {
    "id": 18,
    "title": "Đề Nâng Cao 8",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào nằm giữa 47 và 49?\nA. 46<br>B. 48<br>C. 50<br>D. 57\n\n**Câu 2.** Số nào có hàng đơn vị bằng 0 và lớn hơn 70?\nA. 60<br>B. 70<br>C. 80<br>D. 71\n\n**Câu 3.** 58 + 21 - 9 =:\nA. 60<br>B. 70<br>C. 79<br>D. 88\n\n**Câu 4.** Số cần điền vào ... - 14 = 55 là:\nA. 41<br>B. 59<br>C. 69<br>D. 79\n\n**Câu 5.** Nếu đồng hồ chỉ 7 giờ đúng, sau 2 giờ nữa là:\nA. 5 giờ<br>B. 7 giờ<br>C. 8 giờ<br>D. 9 giờ\n\n**Câu 6.** Có 4 hình vuông nhỏ ghép thành 1 hình vuông lớn. Tổng số hình vuông là:\nA. 4<br>B. 5<br>C. 6<br>D. 8\n\n### II. Tự luận\n**Câu 7.** Điền dấu >, <, =:\na. 50 + 28 ... 90 - 12<br>b. 66 - 16 ... 25 + 24\nc. 87 - 30 ... 40 + 17<br>d. 34 + 45 ... 100 - 20\n\n**Câu 8.** Tính:\na. 28 + 31 + 10 = ............<br>b. 96 - 24 - 20 = ............\nc. 47 + 12 - 30 = ............<br>d. 75 - 25 + 19 = ............\n\n**Câu 9.** Thư có 72 nhãn dán. Thư dùng 30 nhãn dán để đổi quà, rồi được cô giáo thưởng thêm 15 nhãn dán. Hỏi Thư có bao nhiêu nhãn dán?\nBài giải: ................................................................\n\n**Câu 10.** Tìm 3 số có hai chữ số lớn hơn 80 và bé hơn 90.\n........................................................................\n",
    "answer": "### I. Trắc nghiệm\n1. B\n2. C\n3. B\n4. C\n5. D\n6. B\n\n### II. Tự luận\n**Câu 7:**\na. =\nb. >\nc. =\nd. <\n\n**Câu 8:**\na. 69\nb. 52\nc. 29\nd. 69\n\n**Câu 9:**\nSố nhãn dán Thư có là:\n72 - 30 + 15 = 57 (nhãn dán)\nĐáp số: 57 nhãn dán.\n\n**Câu 10:**\nCó thể viết: 81, 82, 83 (hoặc các số khác từ 81 đến 89).\n"
  },
  {
    "id": 19,
    "title": "Đề Nâng Cao 9",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số nào có hàng chục lớn hơn 5 và hàng đơn vị bé hơn 3?\nA. 42<br>B. 61<br>C. 53<br>D. 75\n\n**Câu 2.** 90 - 40 + 7 =:\nA. 43<br>B. 47<br>C. 57<br>D. 67\n\n**Câu 3.** 35 + 24 + 10 =:\nA. 59<br>B. 69<br>C. 79<br>D. 89\n\n**Câu 4.** Biểu thức nào bằng 58?\nA. 80 - 20<br>B. 46 + 12<br>C. 70 - 11<br>D. 35 + 20\n\n**Câu 5.** Ngày 30 tháng 6 là thứ Ba. Ngày 1 tháng 7 là:\nA. thứ Hai<br>B. thứ Ba<br>C. thứ Tư<br>D. thứ Năm\n\n**Câu 6.** Hình có 4 cạnh, 4 góc, các cạnh đối diện bằng nhau là:\nA. hình tròn<br>B. hình tam giác<br>C. hình chữ nhật<br>D. đoạn thẳng\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 73, 37, 70, 77, 30 theo thứ tự bé đến lớn.\n........................................................................\n\n**Câu 8.** Tìm x:\na. x + 32 = 86<br>b. x - 25 = 43<br>c. 99 - x = 54<br>d. 47 + x = 79\n\n**Câu 9.** Nam có 45 thẻ bài. Nam cho em 12 thẻ, cho bạn 10 thẻ. Hỏi Nam còn bao nhiêu thẻ bài?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 24 + ... = 64<br>b. 86 - ... = 56\nc. ... + 12 = 79<br>d. ... - 30 = 48\n",
    "answer": "### I. Trắc nghiệm\n1. B\n2. C\n3. B\n4. B\n5. C\n6. C\n\n### II. Tự luận\n**Câu 7:**\n30, 37, 70, 73, 77.\n\n**Câu 8:**\na. x = 54\nb. x = 68\nc. x = 45\nd. x = 32\n\n**Câu 9:**\nSố thẻ bài Nam còn lại là:\n45 - 12 - 10 = 23 (thẻ bài)\nĐáp số: 23 thẻ bài.\n\n**Câu 10:**\na. 40\nb. 30\nc. 67\nd. 78\n"
  },
  {
    "id": 20,
    "title": "Đề Nâng Cao 10",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số lớn nhất bé hơn 100 là:\nA. 98<br>B. 99<br>C. 100<br>D. 90\n\n**Câu 2.** Số bé nhất lớn hơn 89 là:\nA. 88<br>B. 89<br>C. 90<br>D. 91\n\n**Câu 3.** 64 + 25 - 30 =:\nA. 49<br>B. 59<br>C. 69<br>D. 89\n\n**Câu 4.** 100 - 50 + 18 =:\nA. 58<br>B. 68<br>C. 78<br>D. 88\n\n**Câu 5.** Dãy nào được sắp xếp từ lớn đến bé?\nA. 45, 54, 64<br>B. 80, 70, 60<br>C. 39, 49, 59<br>D. 12, 21, 31\n\n**Câu 6.** Nếu một hình tam giác có 3 cạnh, 3 đỉnh. Hai hình tam giác riêng biệt có tất cả:\nA. 3 cạnh<br>B. 4 cạnh<br>C. 6 cạnh<br>D. 8 cạnh\n\n### II. Tự luận\n**Câu 7.** Viết các số có hai chữ số mà hàng chục là 9, hàng đơn vị bé hơn 5.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 54 + 35 = ............<br>b. 98 - 46 = ............\nc. 67 + 21 = ............<br>d. 89 - 24 = ............\n\n**Câu 9.** Một cửa hàng có 96 quyển vở. Buổi sáng bán 30 quyển, buổi chiều bán 25 quyển. Hỏi cửa hàng còn bao nhiêu quyển vở?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, =:\na. 78 - 20 ... 40 + 18<br>b. 25 + 34 ... 90 - 31\nc. 100 - 10 ... 80 + 9<br>d. 66 + 3 ... 70 - 1\n",
    "answer": "### I. Trắc nghiệm\n1. B\n2. C\n3. B\n4. B\n5. B\n6. C\n\n### II. Tự luận\n**Câu 7:**\n90, 91, 92, 93, 94.\n\n**Câu 8:**\na. 89\nb. 52\nc. 88\nd. 65\n\n**Câu 9:**\nSố quyển vở cửa hàng còn lại là:\n96 - 30 - 25 = 41 (quyển vở)\nĐáp số: 41 quyển vở.\n\n**Câu 10:**\na. =\nb. =\nc. >\nd. =\n"
  }
];\n\nexamData.push(...advancedExamData);\n