const examData = [
  {
    "id": 1,
    "title": "Đề 1",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 6 chục và 4 đơn vị là:\nA. 46<br>B. 64<br>C. 60<br>D. 40\n\n**Câu 2.** Số 89 đọc là:\nA. tám chín<br>B. tám mươi chín<br>C. chín mươi tám<br>D. tám mươi\n\n**Câu 3.** Số lớn nhất trong các số 72, 27, 70, 79 là:\nA. 72<br>B. 27<br>C. 70<br>D. 79\n\n**Câu 4.** Kết quả của 35 + 20 là:\nA. 37<br>B. 55<br>C. 53<br>D. 15\n\n**Câu 5.** Hôm nay là thứ Ba, ngày 12 tháng 4. Ngày mai là:\nA. thứ Tư, ngày 13 tháng 4<br>B. thứ Hai, ngày 11 tháng 4<br>C. thứ Ba, ngày 13 tháng 4<br>D. thứ Năm, ngày 14 tháng 4\n\n**Câu 6.** Hình nào có 4 cạnh bằng nhau?\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 48, 84, 54, 45 theo thứ tự bé đến lớn.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 46 + 23 = ............<br>b. 78 - 35 = ............\nc. 30 + 49 = ............<br>d. 96 - 40 = ............\n\n**Câu 9.** Lan có 24 viên bi, Minh có 15 viên bi. Hỏi hai bạn có tất cả bao nhiêu viên bi?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, = vào chỗ chấm:\na. 57 ... 75<br>b. 68 - 20 ... 48<br>c. 34 + 5 ... 40<br>d. 90 ... 89\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. B  \n3. D  \n4. B  \n5. A  \n6. C  \n\n### II. Tự luận\n**Câu 7:** 45, 48, 54, 84.  \n\n**Câu 8:**  \na. 69  \nb. 43  \nc. 79  \nd. 56  \n\n**Câu 9:**  \nSố viên bi hai bạn có tất cả là:  \n24 + 15 = 39 (viên bi)  \nĐáp số: 39 viên bi.  \n\n**Câu 10:**  \na. <  \nb. =  \nc. <  \nd. >  \n"
  },
  {
    "id": 2,
    "title": "Đề 2",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 53 gồm:\nA. 5 chục 3 đơn vị<br>B. 3 chục 5 đơn vị<br>C. 5 đơn vị 3 chục<br>D. 50 chục 3 đơn vị\n\n**Câu 2.** Số liền trước của 70 là:\nA. 71<br>B. 69<br>C. 60<br>D. 79\n\n**Câu 3.** Kết quả của 86 - 4 là:\nA. 82<br>B. 80<br>C. 46<br>D. 90\n\n**Câu 4.** Các số 31, 33, 35, ... Số cần điền là:\nA. 34<br>B. 36<br>C. 37<br>D. 38\n\n**Câu 5.** Đồng hồ chỉ 8 giờ đúng khi:\nA. kim ngắn chỉ 8, kim dài chỉ 12<br>B. kim ngắn chỉ 12, kim dài chỉ 8<br>C. kim ngắn chỉ 6, kim dài chỉ 12<br>D. kim ngắn chỉ 8, kim dài chỉ 6\n\n**Câu 6.** Trong các hình: hình tròn, hình tam giác, hình vuông, hình chữ nhật, hình không có cạnh là:\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Viết các số: ba mươi bảy, sáu mươi mốt, chín mươi, năm mươi tám.\n........................................................................\n\n**Câu 8.** Tính:\na. 42 + 17 = ............<br>b. 95 - 52 = ............\nc. 61 + 8 = .............<br>d. 77 - 7 = .............\n\n**Câu 9.** Trong vườn có 36 cây hoa hồng và 20 cây hoa cúc. Hỏi trong vườn có tất cả bao nhiêu cây hoa?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 45 = 40 + ...<br>b. 68 = ... + 8<br>c. 90 = 9 chục và ... đơn vị<br>d. 7 chục 2 đơn vị = ...\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. B  \n3. A  \n4. C  \n5. A  \n6. A  \n\n### II. Tự luận\n**Câu 7:** 37, 61, 90, 58.  \n\n**Câu 8:**  \na. 59  \nb. 43  \nc. 69  \nd. 70  \n\n**Câu 9:**  \nSố cây hoa trong vườn có tất cả là:  \n36 + 20 = 56 (cây hoa)  \nĐáp số: 56 cây hoa.  \n\n**Câu 10:**  \na. 5  \nb. 60  \nc. 0  \nd. 72  \n"
  },
  {
    "id": 3,
    "title": "Đề 3",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 76 đọc là:\nA. bảy sáu<br>B. bảy mươi sáu<br>C. sáu mươi bảy<br>D. bảy mươi\n\n**Câu 2.** Số bé nhất trong các số 64, 46, 60, 69 là:\nA. 64<br>B. 46<br>C. 60<br>D. 69\n\n**Câu 3.** Kết quả của 40 + 30 là:\nA. 43<br>B. 70<br>C. 10<br>D. 73\n\n**Câu 4.** 58 - ... = 50. Số cần điền là:\nA. 5<br>B. 8<br>C. 50<br>D. 58\n\n**Câu 5.** Một tuần có:\nA. 5 ngày<br>B. 6 ngày<br>C. 7 ngày<br>D. 8 ngày\n\n**Câu 6.** Hình tam giác có:\nA. 2 cạnh<br>B. 3 cạnh<br>C. 4 cạnh<br>D. không có cạnh\n\n### II. Tự luận\n**Câu 7.** Điền dấu >, <, =:\na. 63 ... 36<br>b. 70 + 5 ... 75<br>c. 88 - 8 ... 79<br>d. 40 + 20 ... 62\n\n**Câu 8.** Đặt tính rồi tính:\na. 25 + 34 = ............<br>b. 89 - 27 = ............\nc. 56 + 3 = .............<br>d. 64 - 30 = ............\n\n**Câu 9.** Mẹ mua 45 quả cam, đã ăn 12 quả. Hỏi còn lại bao nhiêu quả cam?\nBài giải: ................................................................\n\n**Câu 10.** Vẽ thêm vào mỗi hình cho đủ:\na. Một hình vuông có 4 cạnh.  \nb. Một hình tam giác có 3 đỉnh.  \nc. Một hình chữ nhật có 4 góc.\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. B  \n3. B  \n4. B  \n5. C  \n6. B  \n\n### II. Tự luận\n**Câu 7:**  \na. >  \nb. =  \nc. >  \nd. <  \n\n**Câu 8:**  \na. 59  \nb. 62  \nc. 59  \nd. 34  \n\n**Câu 9:**  \nSố quả cam còn lại là:  \n45 - 12 = 33 (quả cam)  \nĐáp số: 33 quả cam.  \n\n**Câu 10:**  \nHọc sinh tự vẽ hình theo yêu cầu.\n"
  },
  {
    "id": 4,
    "title": "Đề 4",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 9 chục và 0 đơn vị là:\nA. 9<br>B. 90<br>C. 99<br>D. 09\n\n**Câu 2.** Số liền sau của 58 là:\nA. 57<br>B. 59<br>C. 68<br>D. 60\n\n**Câu 3.** Phép tính có kết quả bằng 47 là:\nA. 40 + 7<br>B. 47 - 7<br>C. 37 + 5<br>D. 57 - 20\n\n**Câu 4.** 93 - 40 =:\nA. 50<br>B. 53<br>C. 63<br>D. 97\n\n**Câu 5.** Nếu hôm qua là thứ Năm thì hôm nay là:\nA. thứ Tư<br>B. thứ Năm<br>C. thứ Sáu<br>D. thứ Bảy\n\n**Câu 6.** Độ dài của bút chì thường được đo bằng:\nA. cm<br>B. l<br>C. kg<br>D. giờ\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 90, 19, 91, 99 theo thứ tự lớn đến bé.\n........................................................................\n\n**Câu 8.** Tính:\na. 67 - 25 = ............<br>b. 38 + 41 = ............\nc. 80 - 30 = ............<br>d. 24 + 5 = .............\n\n**Câu 9.** Lớp 1A có 32 bạn nữ và 25 bạn nam. Hỏi lớp 1A có tất cả bao nhiêu bạn?\nBài giải: ................................................................\n\n**Câu 10.** Điền số vào chỗ chấm:\na. ... + 20 = 65<br>b. 78 - ... = 70<br>c. 30 + ... = 39<br>d. ... - 4 = 82\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. B  \n3. A  \n4. B  \n5. C  \n6. A  \n\n### II. Tự luận\n**Câu 7:** 99, 91, 90, 19.  \n\n**Câu 8:**  \na. 42  \nb. 79  \nc. 50  \nd. 29  \n\n**Câu 9:**  \nSố bạn lớp 1A có tất cả là:  \n32 + 25 = 57 (bạn)  \nĐáp số: 57 bạn.  \n\n**Câu 10:**  \na. 45  \nb. 8  \nc. 9  \nd. 86  \n"
  },
  {
    "id": 5,
    "title": "Đề 5",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 41 gồm:\nA. 4 chục 1 đơn vị<br>B. 1 chục 4 đơn vị<br>C. 4 đơn vị 1 chục<br>D. 41 chục\n\n**Câu 2.** 100 là số:\nA. có 1 chữ số<br>B. có 2 chữ số<br>C. có 3 chữ số<br>D. bé hơn 99\n\n**Câu 3.** Kết quả của 59 - 9 là:\nA. 50<br>B. 58<br>C. 49<br>D. 68\n\n**Câu 4.** Số cần điền: 22, 24, 26, ..., 30\nA. 27<br>B. 28<br>C. 29<br>D. 31\n\n**Câu 5.** 1 chục que tính là:\nA. 1 que<br>B. 10 que<br>C. 11 que<br>D. 100 que\n\n**Câu 6.** Hình chữ nhật có:\nA. 3 cạnh<br>B. 4 cạnh<br>C. 5 cạnh<br>D. không có cạnh\n\n### II. Tự luận\n**Câu 7.** Viết số thích hợp vào chỗ chấm:\na. 6 chục 7 đơn vị = ...<br>b. 4 chục 0 đơn vị = ...\nc. 82 = ... chục ... đơn vị<br>d. 95 = ... + ...\n\n**Câu 8.** Đặt tính rồi tính:\na. 52 + 16 = ............<br>b. 74 - 21 = ............\nc. 37 + 40 = ............<br>d. 98 - 6 = .............\n\n**Câu 9.** Nam có 58 nhãn vở. Nam cho bạn 20 nhãn vở. Hỏi Nam còn lại bao nhiêu nhãn vở?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, =:\na. 45 + 10 ... 54<br>b. 76 - 6 ... 70<br>c. 33 ... 30 + 3<br>d. 99 ... 100\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. C  \n3. A  \n4. B  \n5. B  \n6. B  \n\n### II. Tự luận\n**Câu 7:**  \na. 67  \nb. 40  \nc. 8 chục 2 đơn vị  \nd. 90 + 5  \n\n**Câu 8:**  \na. 68  \nb. 53  \nc. 77  \nd. 92  \n\n**Câu 9:**  \nSố nhãn vở Nam còn lại là:  \n58 - 20 = 38 (nhãn vở)  \nĐáp số: 38 nhãn vở.  \n\n**Câu 10:**  \na. >  \nb. =  \nc. =  \nd. <  \n"
  },
  {
    "id": 6,
    "title": "Đề 6",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 28 đọc là:\nA. hai tám<br>B. hai mươi tám<br>C. tám mươi hai<br>D. hai mươi\n\n**Câu 2.** Số lớn hơn 65 và bé hơn 67 là:\nA. 64<br>B. 65<br>C. 66<br>D. 67\n\n**Câu 3.** 70 + 6 =:\nA. 67<br>B. 76<br>C. 706<br>D. 13\n\n**Câu 4.** 84 - 30 =:\nA. 54<br>B. 81<br>C. 87<br>D. 50\n\n**Câu 5.** Tháng 5 có:\nA. 28 ngày<br>B. 29 ngày<br>C. 30 ngày<br>D. 31 ngày\n\n**Câu 6.** Vật nào thường có dạng hình tròn?\nA. mặt đồng hồ<br>B. quyển sách<br>C. bảng lớp<br>D. viên gạch\n\n### II. Tự luận\n**Câu 7.** Sắp xếp các số 17, 71, 70, 77 theo thứ tự bé đến lớn.\n........................................................................\n\n**Câu 8.** Tính:\na. 64 + 25 = ............<br>b. 87 - 43 = ............\nc. 20 + 57 = ............<br>d. 69 - 9 = .............\n\n**Câu 9.** Bố có 40 con gà, mẹ mua thêm 18 con gà. Hỏi nhà em có tất cả bao nhiêu con gà?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 29, 30, 31, ..., 33<br>b. 80, 70, 60, ..., 40\nc. 15 + ... = 35<br>d. 96 - ... = 76\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. C  \n3. B  \n4. A  \n5. D  \n6. A  \n\n### II. Tự luận\n**Câu 7:** 17, 70, 71, 77.  \n\n**Câu 8:**  \na. 89  \nb. 44  \nc. 77  \nd. 60  \n\n**Câu 9:**  \nSố con gà nhà em có tất cả là:  \n40 + 18 = 58 (con gà)  \nĐáp số: 58 con gà.  \n\n**Câu 10:**  \na. 32  \nb. 50  \nc. 20  \nd. 20  \n"
  },
  {
    "id": 7,
    "title": "Đề 7",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 3 chục và 8 đơn vị là:\nA. 83<br>B. 38<br>C. 30<br>D. 8\n\n**Câu 2.** Số bé nhất có hai chữ số là:\nA. 1<br>B. 9<br>C. 10<br>D. 11\n\n**Câu 3.** Kết quả của 46 + 3 là:\nA. 43<br>B. 49<br>C. 76<br>D. 19\n\n**Câu 4.** 92 - 50 =:\nA. 42<br>B. 47<br>C. 52<br>D. 90\n\n**Câu 5.** Thứ Ba, thứ Tư, thứ Năm, ..., thứ Bảy. Từ còn thiếu là:\nA. thứ Hai<br>B. thứ Sáu<br>C. Chủ nhật<br>D. thứ Ba\n\n**Câu 6.** Hình nào có 3 đỉnh?\nA. hình tròn<br>B. hình vuông<br>C. hình tam giác<br>D. hình chữ nhật\n\n### II. Tự luận\n**Câu 7.** Viết các số sau theo thứ tự từ 55 đến 60.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 31 + 48 = ............<br>b. 75 - 32 = ............\nc. 44 + 20 = ............<br>d. 89 - 7 = .............\n\n**Câu 9.** Trên cành cây có 27 con chim, sau đó có 12 con bay đi. Hỏi trên cành cây còn lại bao nhiêu con chim?\nBài giải: ................................................................\n\n**Câu 10.** Điền dấu >, <, =:\na. 60 ... 6 chục<br>b. 72 ... 27<br>c. 81 - 1 ... 79<br>d. 25 + 4 ... 30\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. C  \n3. B  \n4. A  \n5. B  \n6. C  \n\n### II. Tự luận\n**Câu 7:** 55, 56, 57, 58, 59, 60.  \n\n**Câu 8:**  \na. 79  \nb. 43  \nc. 64  \nd. 82  \n\n**Câu 9:**  \nSố con chim trên cành cây còn lại là:  \n27 - 12 = 15 (con chim)  \nĐáp số: 15 con chim.  \n\n**Câu 10:**  \na. =  \nb. >  \nc. >  \nd. <  \n"
  },
  {
    "id": 8,
    "title": "Đề 8",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 95 gồm:\nA. 9 chục 5 đơn vị<br>B. 5 chục 9 đơn vị<br>C. 9 đơn vị 5 chục<br>D. 95 đơn vị\n\n**Câu 2.** Số liền trước của 100 là:\nA. 98<br>B. 99<br>C. 101<br>D. 90\n\n**Câu 3.** Kết quả của 23 + 34 là:\nA. 57<br>B. 56<br>C. 47<br>D. 67\n\n**Câu 4.** Phép tính nào có kết quả bé nhất?\nA. 40 + 5<br>B. 60 - 10<br>C. 30 + 8<br>D. 70 - 20\n\n**Câu 5.** Kim dài chỉ số 12, kim ngắn chỉ số 5. Đồng hồ chỉ:\nA. 12 giờ<br>B. 5 giờ<br>C. 6 giờ<br>D. 10 giờ\n\n**Câu 6.** Hình nào có 4 góc?\nA. hình tròn<br>B. hình tam giác<br>C. hình vuông<br>D. đoạn thẳng\n\n### II. Tự luận\n**Câu 7.** Điền số vào tia số:\n41, 42, ..., 44, ..., 46, ...\n\n**Câu 8.** Tính:\na. 58 + 21 = ............<br>b. 97 - 54 = ............\nc. 70 + 9 = .............<br>d. 86 - 6 = .............\n\n**Câu 9.** Cửa hàng có 65 hộp sữa, đã bán 30 hộp. Hỏi cửa hàng còn lại bao nhiêu hộp sữa?\nBài giải: ................................................................\n\n**Câu 10.** Viết tiếp vào chỗ chấm:\na. 3 ngày trong tuần: ...................................................\nb. 2 vật có dạng hình chữ nhật: .........................................\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. B  \n3. A  \n4. C  \n5. B  \n6. C  \n\n### II. Tự luận\n**Câu 7:** 43, 45, 47.  \n\n**Câu 8:**  \na. 79  \nb. 43  \nc. 79  \nd. 80  \n\n**Câu 9:**  \nSố hộp sữa cửa hàng còn lại là:  \n65 - 30 = 35 (hộp sữa)  \nĐáp số: 35 hộp sữa.  \n\n**Câu 10:**  \na. Ví dụ: thứ Hai, thứ Ba, thứ Tư.  \nb. Ví dụ: quyển sách, cái bàn.  \n"
  },
  {
    "id": 9,
    "title": "Đề 9",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số 60 đọc là:\nA. sáu mươi<br>B. sáu không<br>C. sáu chục<br>D. không sáu\n\n**Câu 2.** Trong các số 81, 18, 80, 88, số lớn nhất là:\nA. 81<br>B. 18<br>C. 80<br>D. 88\n\n**Câu 3.** 36 + 12 =:\nA. 48<br>B. 46<br>C. 58<br>D. 24\n\n**Câu 4.** 79 - 20 =:\nA. 57<br>B. 59<br>C. 99<br>D. 70\n\n**Câu 5.** Hôm nay là ngày 16 tháng 3. Ngày hôm qua là:\nA. ngày 15 tháng 3<br>B. ngày 17 tháng 3<br>C. ngày 16 tháng 4<br>D. ngày 14 tháng 3\n\n**Câu 6.** Một đoạn thẳng có:\nA. 1 đầu mút<br>B. 2 đầu mút<br>C. 3 đầu mút<br>D. 4 đầu mút\n\n### II. Tự luận\n**Câu 7.** Viết các số 64, 46, 60, 69 theo thứ tự lớn đến bé.\n........................................................................\n\n**Câu 8.** Đặt tính rồi tính:\na. 43 + 25 = ............<br>b. 88 - 36 = ............\nc. 50 + 28 = ............<br>d. 76 - 5 = .............\n\n**Câu 9.** Mai gấp được 34 ngôi sao, Hoa gấp được 23 ngôi sao. Hỏi hai bạn gấp được tất cả bao nhiêu ngôi sao?\nBài giải: ................................................................\n\n**Câu 10.** Điền số thích hợp:\na. 57 = ... + 7<br>b. 81 = 80 + ...<br>c. 48 - ... = 40<br>d. ... + 30 = 92\n",
    "answer": "### I. Trắc nghiệm\n1. A  \n2. D  \n3. A  \n4. B  \n5. A  \n6. B  \n\n### II. Tự luận\n**Câu 7:** 69, 64, 60, 46.  \n\n**Câu 8:**  \na. 68  \nb. 52  \nc. 78  \nd. 71  \n\n**Câu 9:**  \nSố ngôi sao hai bạn gấp được tất cả là:  \n34 + 23 = 57 (ngôi sao)  \nĐáp số: 57 ngôi sao.  \n\n**Câu 10:**  \na. 50  \nb. 1  \nc. 8  \nd. 62  \n"
  },
  {
    "id": 10,
    "title": "Đề 10",
    "exam": "### I. Trắc nghiệm\n**Câu 1.** Số gồm 8 chục và 2 đơn vị là:\nA. 28<br>B. 82<br>C. 80<br>D. 20\n\n**Câu 2.** Số liền sau của 99 là:\nA. 98<br>B. 90<br>C. 100<br>D. 109\n\n**Câu 3.** Kết quả của 72 - 2 là:\nA. 70<br>B. 74<br>C. 52<br>D. 20\n\n**Câu 4.** Phép tính nào có kết quả bằng 66?\nA. 60 + 6<br>B. 66 - 6<br>C. 56 + 6<br>D. 76 - 20\n\n**Câu 5.** Thứ tự đúng của các tháng là:\nA. tháng 1, tháng 2, tháng 3<br>B. tháng 2, tháng 1, tháng 3<br>C. tháng 3, tháng 2, tháng 1<br>D. tháng 1, tháng 3, tháng 2\n\n**Câu 6.** Vật nào thường có dạng hình vuông?\nA. mặt đồng hồ tròn<br>B. viên gạch lát nền<br>C. quả bóng<br>D. cái bút\n\n### II. Tự luận\n**Câu 7.** Điền dấu >, <, =:\na. 45 ... 54<br>b. 90 - 10 ... 80<br>c. 67 + 2 ... 70<br>d. 100 ... 99\n\n**Câu 8.** Tính:\na. 36 + 42 = ............<br>b. 94 - 31 = ............\nc. 63 + 6 = .............<br>d. 85 - 40 = ............\n\n**Câu 9.** Thu có 56 bông hoa, Thu tặng bạn 24 bông. Hỏi Thu còn lại bao nhiêu bông hoa?\nBài giải: ................................................................\n\n**Câu 10.** Quan sát và trả lời:\na. Hình vuông có .... cạnh.  \nb. Hình tam giác có .... cạnh.  \nc. Hình tròn có .... cạnh.  \nd. Hình chữ nhật có .... góc.\n",
    "answer": "### I. Trắc nghiệm\n1. B  \n2. C  \n3. A  \n4. A  \n5. A  \n6. B  \n\n### II. Tự luận\n**Câu 7:**  \na. <  \nb. =  \nc. <  \nd. >  \n\n**Câu 8:**  \na. 78  \nb. 63  \nc. 69  \nd. 45  \n\n**Câu 9:**  \nSố bông hoa Thu còn lại là:  \n56 - 24 = 32 (bông hoa)  \nĐáp số: 32 bông hoa.  \n\n**Câu 10:**  \na. 4  \nb. 3  \nc. 0 (hoặc không có cạnh)  \nd. 4  \n"
  }
];